### ISSUE TITLE
Large white arrow in upper left corner

### ISSUE THREAD

**Issue by markfirmware** [pik33/ultibo-retro-sid#4]
Is this for a mouse? I don't have a mouse. Can you hide this arrow when it isn't applicable?

**Comment by pik33** [comment]
This will be a mouse cursor when mouse support will be added. Because there is no mouse support yet, it sticks at 0,0 position.  

It may be a good idea to hide it when there is no mouse so I will add a function which will hide the cursor when mouse doesn't move, for example in 5 seconds.

**Comment by pik33** [comment]
In 0.13 version there is no mouse cursor anymore 
It will be added again when I add the mouse support.

**Comment by markfirmware** [comment]
Confirmed in release https://github.com/pik33/ultibo-retro-sid/releases/download/0.13-20161126/sidplay.zip

Thanks
