### ISSUE TITLE
Remove extraneous files from repo and put sidplay.zip in releases

### ISSUE THREAD

**Issue by markfirmware** [pik33/ultibo-retro-sid#5]
These steps will remove extraneous files from your repo, and use github releases for publishing your sidplay.zip installation package.

1. Please follow the instructions at
http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

using this for .gitignore:

```
*.bak
*.compiled
*.elf
*.img
*.lps
*.o
*.ppu
*.s
*.zip
```

2. Then, from now on, publish sidplay.zip to github releases using these instructions:

https://help.github.com/articles/creating-releases/

You would attach sidplay.zip  to the release. You can mark the release as a pre-release.

Thanks,
Mark

**Comment by pik33** [comment]
Removed all these not needed files, made a release. 

I left zip file in the main folder remembering how long I searched executables in other github repositories, using some colorful language when doing this.

**Comment by markfirmware** [comment]
Thank you.
