### ISSUE TITLE
Remove "." from directory listing

### ISSUE THREAD

**Issue by markfirmware** [pik33/ultibo-retro-sid#6]
Can you remove the "." entry from the directory listing? I don't know if you need to keep this to be authentically retro. If not, it really doesn't serve any purpose.

Fyi I tested 0.14. I don't have an ear for the change. I found no problems.

**Comment by markfirmware** [comment]
Would you accept a pull request for this? I can quickly make this change. Mark.

**Comment by pik33** [comment]
The directory displayer is in major rewriting process to allow more than one drive and to make directories to be displayed at the start of the list and not mixed with files.

**Comment by markfirmware** [comment]
(From the forum)
Since the removal of "." might be desirable later, as you say, I suggest creating an issue label "deferred", label the issue as such, and go ahead and close the issue. It can always be re-opened later.
